apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault-store
  namespace: external-secrets
spec:
  provider:
    azurekv:
      environmentType: PublicCloud
      authType: WorkloadIdentity
      vaultUrl: "https://kv-k8s-pluto.vault.azure.net/"
      serviceAccountRef:
        name: external-secrets-sa
