apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-secret2
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault-store
  target:
    name: azure-kv-713-test
  data:
    - secretKey: secret
      remoteRef:
        key: secret